[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[project]
name = "mh_structlog"
authors = [
    { name = "Mathieu Hinderyckx", email = "mathieu.hinderyckx@gmail.com" },
]
description = "Some Structlog configuration and wrappers to easily use structlog."
version = "0.0.1.dev0"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "orjson>=3.11.5",
    "rich>=14.2.0",
    "structlog>=25.5.0",
]
[project.optional-dependencies]
django = [
    "django>=5.0",
]
aws = [
    "aws-lambda-powertools>=3.23.0",
]
sentry = [
    "structlog-sentry>=2.2.1",
]

[tool.setuptools_scm]
version_file = "src/mh_structlog/_version.py"

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=8.38.0",
    "ruff>=0.16.3",
    "ty>=0.0.72",
]
tests = [
    "coverage>=7.13.4",
    "django>=5",
    "filelock>=3.25.0",
    "freezegun>=1.5.5",
    "pydantic>=2.12.5",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "pytest-env>=1.2.0",
    "pytest-randomly>=4.0.1",
    "pytest-sugar>=1.1.1",
    "pytest-xdist>=3.6.1",
    "pytest>=9.0.2",
]

[tool.uv]
required-version = ">=0.10.4"
package = true
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
    "sys_platform == 'win32'",
]

# ==== ruff ====
[tool.ruff]
line-length = 120
indent-width = 4
preview = false
required-version = ">=0.12"
target-version = "py310"
unsafe-fixes = true

# Overwritten in CI/CD
output-format = "full"
fix = true

[tool.ruff.lint]
preview = true
select = [
    # https://docs.astral.sh/ruff/rules/#rules
    "A",
    "AIR",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    # "D",
    "DJ",
    "DOC",
    "DTZ",
    "E",
    "EM",
    "EXE",
    "F",
    "FA",
    "FBT",
    "FLY",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "INT",
    "ISC",
    "LOG",
    "N",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "Q",
    "R",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "SLOT",
    "T10",
    "T20",
    "TC",
    "TID",
    "TRY",
    "UP",
    "YTT",
    # "ERA",   # commented out code; not always best to have it removed forcefully, sometimes want to keep
]

ignore = [
    "missing-type-args",  # Missing type annotations for *args
    "missing-type-kwargs",  # Missing type annotations for **kwargs
    "missing-return-type-special-method",  # Missing return type annotation for special method `__init__`
    "any-type",  # Disallow Any type hints
    "missing-trailing-comma",  # Trailing comma missing. The ruff format always removes this on e.g. a list of function arguments.
    "undocumented-public-module",    # Missing docstring in public module
    "undocumented-magic-method",    # Missing docstring in magic method
    "undocumented-public-nested-class",    # Missing docstring in public nested class
    "blank-line-after-function",    # No blank line after function docstring
    "line-too-long",    # Line too long
    "raw-string-in-exception",   # Exception must not use a string literal, assign to variable first
    "f-string-in-exception",   # Exception must not use an f-string literal, assign to variable first
    "single-line-implicit-string-concatenation",  # Conflicting with formatter
    "pandas-use-of-dot-values",   # pandas-use-of-dot-values. Ignored because it gives a lot of false positives every time .values is used on something.
    "bad-quotes-inline-string",    # Single quotes found but double quotes preferred
    "mutable-class-default",  # mutable-class-default. Class attributes would required type annotations everywhere if enabled.
    "raise-vanilla-class",  # Create your own exception
    "raise-vanilla-args",  # Avoid specifying long messages outside the exception class
    "blanket-type-ignore",  # Require specific codes when silencing linting.
    "boolean-type-hint-positional-argument",  # Boolean arguments in function calls
    "boolean-default-value-positional-argument",  # Boolean arguments in function calls
    "unused-noqa",  # Report unused noqa directives. This clashes with the leniency from the ignore above this one.
    "docstring-missing-exception",  # Raised exception {id} missing from docstring
    "no-self-use", # Not using self in a method
    "docstring-missing-returns",  # Not mentioning 'return' explicitly in a docstring
    "stdlib-module-shadowing",    # Module name is shadowing a python builtin module
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = ["print"]

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
preview = false
line-ending = "auto"
indent-style = "space"
quote-style = "preserve"
docstring-code-format = true
docstring-code-line-length = "dynamic"
exclude = ["*.pyi", "__pypackages__/", ".venv/", "env/", "venv/", ".git/", ".hg/", ".mypy_cache/", ".tox/", ".nox/", ".pytest_cache/", ".ruff_cache/"]


# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = true

# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["module-import-not-at-top-of-file", "undocumented-public-package", "undefined-local-with-import-star"]
"**/{tests,docs,tools}/*" = [
    "missing-return-type-undocumented-public-function",
    "unused-function-argument",
    "unused-method-argument",
    "undocumented-public-class",
    "undocumented-public-method",
    "undocumented-public-function",
    "docstring-missing-yields",
    "django-model-without-dunder-str",
    "module-import-not-at-top-of-file",
    "import-private-name",
    "too-many-locals",
    "too-many-statements",
    "magic-value-comparison",
    "assert",
    "hardcoded-password-string",
    "suspicious-non-cryptographic-random-usage",
    "private-member-access",
]
"test*.py" = [
    "missing-return-type-undocumented-public-function",
    "unused-function-argument",
    "unused-method-argument",
    "undocumented-public-class",
    "undocumented-public-method",
    "undocumented-public-function",
    "docstring-missing-yields",
    "django-model-without-dunder-str",
    "module-import-not-at-top-of-file",
    "import-private-name",
    "too-many-locals",
    "too-many-statements",
    "magic-value-comparison",
    "assert",
    "hardcoded-password-string",
    "suspicious-non-cryptographic-random-usage",
    "private-member-access",
]

[tool.ruff.lint.pylint]
max-args = 20
max-positional-args = 20

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
avoid-escape = true

[tool.ruff.lint.flake8-annotations]
allow-star-arg-any = true
ignore-fully-untyped = true     # allows for gradual typing
suppress-none-returning = false

[tool.ruff.lint.flake8-unused-arguments]
ignore-variadic-names = true

[tool.ruff.lint.isort]
force-single-line = false
combine-as-imports = true
force-wrap-aliases = false
detect-same-package = true
split-on-trailing-comma = false
known-local-folder = ["src"]
lines-after-imports = 2

# ==== pytest ====
[tool.pytest_env]
ENVIRONMENT = "test"
COLOR = 1

[tool.pytest]
addopts = ["-s", "--durations=5", "-v", "--import-mode=importlib", "--cov", "--cov-report=term", "--cov-report=html", "--cov-report=xml", "--junit-xml=junit.xml"]

junit_family = 'xunit2'
junit_suite_name = "test_suite"
junit_logging = 'all'
junit_log_passing_tests = true
junit_duration_report = "call"

python_files = ["*/tests.py", "*/test_*.py", "*/tests_*.py", "*/*.py"]
testpaths = ["tests", "src"]

filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]

# ==== Coverage ====
[tool.coverage.run]
omit = [
    "*/migrations/*",
    "*/media/*",
    ".venv/*",
    "terraform/*",
    "htmlcov/*",
    "staticfiles/*",
    "requirements/*",
    "manage.py",
    "asgi.py",
    "wsgi.py",
    "*/.vscode/*",
]
plugins = []
branch = true

[tool.coverage.report]
format = "text"
skip_empty = false
precision = 2

[tool.coverage.term]

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"
